IF(SELECT TOP 1 1 FROM SYSOBJECTS WHERE TYPE = 'U' AND NAME = 'TB_Lista_Tarefas') IS NOT NULL
BEGIN
	DROP TABLE [DBO].[TB_Lista_Tarefas]
END

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [DBO].[TB_Lista_Tarefas](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[Tarefa] [VARCHAR](100) NOT NULL,
	[Status] [VARCHAR](30) NOT NULL,
	[Responsavel] [VARCHAR](50) NOT NULL,
	[Prioridade] [VARCHAR](50) NOT NULL
PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO